name: Build Electron App
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./army  # هذا السطر يجبره على الدخول لمجلد army

      - name: Build
        run: npm run electron:build
        working-directory: ./army  # هذا السطر يضمن تنفيذ البناء داخل المجلد الصحيح
