name: Build Electron App
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show all files
        run: dir /s /b
        shell: cmd

      - name: Install dependencies
        run: npm install
        # سنقوم بتعديل هذا السطر بناءً على نتيجة الخطوة السابقة

      - name: Build
        run: npm run electron:build
